# Generated by Django 6.0.3 on 2026-05-11 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_result_ca_score_remove_result_exam_score_and_more'),
        ('profiles', '0003_remove_teacherprofile_subjects'),
        ('schools', '0004_activitylog_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROMOTED', 'Promoted'), ('REPEATING', 'Repeating'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=15)),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classarm')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='profiles.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'session')},
            },
        ),
    ]
