# Generated by Django 6.0.3 on 2026-05-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=15),
        ),
    ]
