# Generated by Django 6.0.3 on 2026-05-16 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_studentprofile_status_teacherprofile_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admission_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='disability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='entry_term',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fee_plan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='genotype',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_nin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='previous_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='previous_school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Onboarding)'), ('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
