# Generated by Django 6.0.3 on 2026-05-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_teacherrole_teacherprofile_assigned_class_arm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='class_arm',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='onboarding_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='onboarding_token_expires_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='onboarding_token_expires_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('INACTIVE', 'Inactive')], default='PENDING_REVIEW', max_length=15),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='onboarding_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
