# Generated by Django 6.0.3 on 2026-05-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_studentprofile_class_arm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='section',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(choices=[('JUNIOR', 'Junior Secondary (General)'), ('SCIENCE', 'Senior Secondary - Sciences'), ('ARTS_HUMANITIES', 'Senior Secondary - Arts & Humanities'), ('COMMERCIAL', 'Senior Secondary - Commercial'), ('VOCATIONAL_TRADE', 'Senior Secondary - Vocational & Trades')], default='JUNIOR', max_length=20),
        ),
    ]
