# Generated by Django 6.0.3 on 2026-05-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_subject_category'),
        ('profiles', '0009_remove_studentprofile_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='class_arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.classarm'),
        ),
    ]
