# Generated by Django 6.0.3 on 2026-05-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_studentprofile_class_arm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='onboarding_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
