# Generated by Django 6.0.3 on 2026-05-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_teacherprofile_onboarding_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='onboarding_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
