# Generated by Django 6.0.3 on 2026-06-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_remove_classarm_subjects_class_core_subjects_and_more'),
        ('profiles', '0012_alter_studentprofile_onboarding_token_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subject_assignments',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='academics.subjectassignment'),
        ),
    ]
