# Generated by Django 6.0.3 on 2026-10-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_remove_teacherprofile_subject_assignments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherprofile",
            name="assigned_class_arm",
        ),
    ]
