# Generated by Django 6.0.3 on 2026-05-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_middle_name_user_religion_user_state_of_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'System Super Admin'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('BURSAR', 'Bursar'), ('STUDENT', 'Student')], max_length=20),
        ),
    ]
