# Generated by Django 6.0.3 on 2026-05-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_academicterm_result_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning/Admission'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='PLANNING', max_length=10),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='grading_deadline',
            field=models.DateTimeField(blank=True, help_text='After this date, teachers cannot edit marks without Admin override.', null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='next_term_begins',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='sequence',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 for First, 2 for Second, etc. Helps with trend graphs', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='grading_system',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage (0-100)'), ('GPA', 'GPA (4.0/5.0)')], default='PERCENTAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='pass_mark',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='school',
            name='timezone',
            field=models.CharField(default='Africa/Lagos', max_length=50),
        ),
    ]
