# Generated by Django 6.0.3 on 2026-05-11 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_academicsession_end_date_academicsession_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic (Grades/Attendance)'), ('FINANCE', 'Finance (Fees/Payments)'), ('USER', 'User Management (Enrollment/Profiles)'), ('SYSTEM', 'System (Settings/Announcements)')], default='SYSTEM', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Extra details or reasons for the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('audience', models.CharField(choices=[('ALL', 'Everyone'), ('TEACHERS', 'Teachers Only'), ('STUDENTS', 'Students & Parents'), ('ADMINS', 'Admins Only')], default='ALL', max_length=15)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned announcements stay at the top of the feed.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Announcement will be hidden after this date.', null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='schools.school')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
