# Generated by Django 6.0.3 on 2026-09-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_activitylog_announcement"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="academicsession",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="school",
        ),
        migrations.AlterField(
            model_name="academicsession",
            name="name",
            field=models.CharField(
                help_text="e.g. 2025/2026", max_length=10, unique=True
            ),
        ),
        migrations.RemoveField(
            model_name="academicsession",
            name="school",
        ),
    ]
