# Generated by Django 6.0.3 on 2026-04-19 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('profiles', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classarm',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classarm',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='result',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicterm'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='classarm',
            name='subjects',
            field=models.ManyToManyField(related_name='arms', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='class_arm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.classarm'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicsession'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='subject_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.subjectassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('class_arm', 'subject', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'subject_assignment', 'term')},
        ),
    ]
