# Generated by Django 6.0.3 on 2026-04-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='class',
            name='order',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
