# Generated by Django 6.0.3 on 2026-04-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_class_options_class_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(choices=[('JSS1', 'JSS 1'), ('JSS2', 'JSS 2'), ('JSS3', 'JSS 3'), ('SSS1', 'SSS 1'), ('SSS2', 'SSS 2'), ('SSS3', 'SSS 3')], max_length=20),
        ),
    ]
