# Generated by Django 6.0.3 on 2026-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('CORE', 'General Core'), ('JUNIOR', 'Junior Secondary'), ('SCIENCE', 'Senior Science'), ('ARTS', 'Senior Arts'), ('COMMERCIAL', 'Senior Commercial')], default='CORE', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
