# Generated by Django 6.0.3 on 2026-04-22 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_subject_name_alter_subject_unique_together'),
        ('profiles', '0003_remove_teacherprofile_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectassignment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='profiles.teacherprofile'),
        ),
    ]
