# Generated by Django 6.0.3 on 2026-04-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_subject_category_alter_subject_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classarm',
            name='subjects',
            field=models.ManyToManyField(related_name='arms', to='academics.subject'),
        ),
    ]
