# Generated by Django 6.0.3 on 2026-05-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_result_ca_score_remove_result_exam_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='school',
        ),
        migrations.RemoveField(
            model_name='classarm',
            name='school',
        ),
        migrations.RemoveField(
            model_name='gradecomponent',
            name='school',
        ),
        migrations.RemoveField(
            model_name='period',
            name='school',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'code')},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
    ]
