# Generated by Django 6.0.3 on 2026-05-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_class_school_remove_classarm_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('JNR_CORE', 'Junior Core'), ('SNR_CORE', 'Senior Core'), ('JUNIOR', 'Junior Secondary'), ('SCIENCE', 'Senior Science'), ('ARTS', 'Senior Arts'), ('COMMERCIAL', 'Senior Commercial'), ('VOCATIONAL_TRADE', 'Vocational Trade')], default='CORE', max_length=20),
        ),
    ]
