# Generated by Django 6.0.3 on 2026-05-31 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_subject_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(choices=[('JSS1', 'Junior Secondary School 1'), ('JSS2', 'Junior Secondary School 2'), ('JSS3', 'Junior Secondary School 3'), ('SSS1', 'Senior Secondary School 1'), ('SSS2', 'Senior Secondary School 2'), ('SSS3', 'Senior Secondary School 3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='classarm',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_arms', to='academics.class'),
        ),
    ]
