# Generated by Django 6.0.3 on 2026-06-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_class_name_alter_classarm_class_level'),
        ('profiles', '0012_alter_studentprofile_onboarding_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classarm',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='profiles.teacherprofile'),
        ),
    ]
