# Generated by Django 6.0.3 on 2026-06-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_classarm_class_teacher'),
        ('profiles', '0012_alter_studentprofile_onboarding_token_expires_at'),
        ('schools', '0004_activitylog_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classarm',
            name='subjects',
        ),
        migrations.AddField(
            model_name='class',
            name='core_subjects',
            field=models.ManyToManyField(blank=True, related_name='core_subjects', to='academics.subject'),
        ),
        migrations.CreateModel(
            name='StudentSubjectChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_choices', to='profiles.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'session')},
            },
        ),
    ]
