# Generated by Django 6.0.3 on 2026-10-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0012_remove_classarm_subjects_class_core_subjects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="category",
            field=models.CharField(
                choices=[
                    ("JNR_CORE", "Junior Core"),
                    ("SNR_CORE", "Senior Core"),
                    ("JUNIOR", "Junior Secondary"),
                    ("SCIENCE", "Senior Science"),
                    ("ARTS", "Senior Arts"),
                    ("COMMERCIAL", "Senior Commercial"),
                    ("VOCATIONAL_TRADE", "Vocational Trade"),
                ],
                default="JNR_CORE",
                max_length=20,
            ),
        ),
    ]
