# Generated by Django 6.0.3 on 2026-10-09 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0013_cleanup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultentry",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="academics.gradecomponent",
            ),
        ),
    ]
